### ISSUE TITLE
Impossible to find output_default

### ISSUE THREAD

**Issue by william-denault** [DongyueXie/vebpm#3]
Hello Dongyue I am trying to run some of your code of vebpm
 
when running this
```
n = 1000
mu = rnorm(n)
x = rpois(n,exp(mu))
pois_mean_split_mixture(x)
```
I got an error message saying the R cannot find the
`"output_default"`
function.
I cannot figure where to find it. Do you have any input ?

**Comment by DongyueXie** [comment]
I pushed a fix.

BTW, `pois_mean_split` is the function for the splitting method; `pois_mean_split_mixture` is a more complicated splitting method that uses mixture of normals for splitting, it is not studied extensively.
